
import javax.swing.JFrame;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class connexion extends javax.swing.JFrame {

    /**
     * Creates new form connexion
     */
    public connexion() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        textEmail_Connection.setBackground(new java.awt.Color(0,0,0,1));
        textpassword_Connexion.setBackground(new java.awt.Color(0,0,0,1));
        
        
    
       
        // Création du JLabel
        JLabel jLabel2 = new JLabel("Contenu centré horizontalement");
        
        // Création d'un JPanel pour contenir le JLabel
        JPanel panel = new JPanel(new BorderLayout());
        panel.add(jLabel2, BorderLayout.CENTER);
        
        
        // Initialisation du Timer
        visibilityTimer = new Timer(2000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Masquer le mot de passe après la période spécifiée
                textpassword_Connexion.setEchoChar((char)8226);
                eyedisable.setVisible(true);
                eyedisable.setEnabled(true);
                eyeshow.setVisible(false);
                eyeshow.setEnabled(false);
            }
        });
        visibilityTimer.setRepeats(false);  
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        eyedisable = new javax.swing.JLabel();
        eyeshow = new javax.swing.JLabel();
        jButton1_Connexion_ = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textEmail_Connection = new javax.swing.JTextField();
        textpassword_Connexion = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngwing.com (10).png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Connexion !");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 34, 238, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(199, 226, 255));
        jLabel3.setText("Email ou Login");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_user_20px.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("____________________________________________________________");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 440, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(199, 226, 255));
        jLabel6.setText("Mot de passe");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" ___________________________________________________________");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 420, 30));

        eyedisable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_invisible_20px.png"))); // NOI18N
        eyedisable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eyedisable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyedisableMouseClicked(evt);
            }
        });
        jPanel2.add(eyedisable, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        eyeshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_visible_20px.png"))); // NOI18N
        eyeshow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eyeshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeshowMouseClicked(evt);
            }
        });
        jPanel2.add(eyeshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        jButton1_Connexion_.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1_Connexion_.setForeground(new java.awt.Color(25, 118, 211));
        jButton1_Connexion_.setText("Se Connecter");
        jButton1_Connexion_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_Connexion_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Connexion_ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1_Connexion_, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 420, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("S'inscrire ?");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Retour à la page d'accueil !");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Connecter vous pour accéder aux ressources de la bibliothéque.");
        jLabel11.setAlignmentX(5.0F);
        jLabel11.setAlignmentY(0.0F);
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ou inscrivez-vous pour créer votre compte et vous connecter ! :)");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("X");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 0, 20, -1));

        textEmail_Connection.setFont(textEmail_Connection.getFont().deriveFont((float)16));
        textEmail_Connection.setForeground(new java.awt.Color(255, 255, 255));
        textEmail_Connection.setBorder(null);
        jPanel2.add(textEmail_Connection, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 212, 410, 30));

        textpassword_Connexion.setFont(textpassword_Connexion.getFont());
        textpassword_Connexion.setForeground(new java.awt.Color(255, 255, 255));
        textpassword_Connexion.setBorder(null);
        jPanel2.add(textpassword_Connexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 292, 410, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_Connexion_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Connexion_ActionPerformed
        // TODO add your handling code here:
        
        PreparedStatement ps;
        ResultSet rs;
        
        String email_Connect = textEmail_Connection.getText();
        String Mot_de_passe_Connect = String.valueOf(textpassword_Connexion.getPassword());
        
        String query = "SELECT * FROM `utilisateurs` WHERE `Email_Login` = ? AND `Mot_de_Passe` = ? AND (`Fonction` IS NULL OR `Fonction` LIKE '%')";
                
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            
            ps.setString(1, email_Connect);
            ps.setString(2, Mot_de_passe_Connect);
            //ps.setString(3, "Utilisateur"); // Fonction = "Utilisateur"
            //ps.setString(4, "Biblithecaire"); // Fonction = "Biblithecaire"
            
            // Exécution de la requête SQL
            rs = ps.executeQuery();
            
            
            if (rs.next()) { // Vérifie si la requête a renvoyé une ligne
                 //On récupère la valeur de la colonne "Fonction"
                 String Fonction = rs.getString("Fonction");
                 
                 if("Utilisateur".equals(Fonction)) {
                     
                     // Utilisateur
                     Utilisateurs utilisateur = new Utilisateurs(); 
                     utilisateur.setVisible(true);
                     dispose();
                 } 
                 else if ("Bibliothecaire".equals(Fonction)) {
                     
                     // Biblithecaire
                     Tableau_de_bord tableau_de_bord = new Tableau_de_bord(); 
                     tableau_de_bord.setVisible(true);
                     dispose();
                 } 
                 else if(Fonction == null) {
                     JOptionPane.showMessageDialog(null, "ALERTE : Utilisateur non répertorié ");
                 }
             } else {
                         JOptionPane.showMessageDialog(null, "ALERTE : Vous n'êtes pas un abonné de notre bibliothéque\n\nInscrivez vous d'abord pour bénéficier des services de la bibliothéque !!!");
                     }
        } catch (SQLException ex) {
            Logger.getLogger(connexion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1_Connexion_ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
    //System.exit(0);        // TODO add your handling code here:
    dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void eyedisableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyedisableMouseClicked
        // TODO add your handling code here:
        textpassword_Connexion.setEchoChar((char)0);
        eyedisable.setVisible(false);
        eyedisable.setEnabled(false);
        
        eyeshow.setVisible(true);
        eyeshow.setEnabled(true);
        
         // Définir une période de visibilité de 3 secondes pour eyedisable
        visibilityTimer.setDelay(3000);
        visibilityTimer.start();
        
    }//GEN-LAST:event_eyedisableMouseClicked

    private void eyeshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeshowMouseClicked
        // TODO add your handling code here:
        textpassword_Connexion.setEchoChar((char)8226);
        eyedisable.setVisible(true);
        eyedisable.setEnabled(true);
        
        eyeshow.setVisible(false);
        eyeshow.setEnabled(false);
        
        
        // Définir une période de visibilité de 5 secondes pour eyeshow
        visibilityTimer.setDelay(5000);
        visibilityTimer.start();
    }//GEN-LAST:event_eyeshowMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        inscription inscription  = new inscription(); 
        inscription .setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        accueil accueil  = new accueil(); 
        accueil.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(connexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new connexion().setVisible(true);
            }
        });
    }
    private Timer visibilityTimer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eyedisable;
    private javax.swing.JLabel eyeshow;
    private javax.swing.JButton jButton1_Connexion_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField textEmail_Connection;
    private javax.swing.JPasswordField textpassword_Connexion;
    // End of variables declaration//GEN-END:variables
}
