
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import java.awt.event.*;
import java.awt.*;
import javax.swing.JComponent;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class inscription extends javax.swing.JFrame {

    /**
     * Creates new form inscription
     */
    public inscription() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        textprénom_Inscription.setBackground(new java.awt.Color(0,0,0,1));
        textnom_Inscription.setBackground(new java.awt.Color(0,0,0,1));
        textadresse__Inscription.setBackground(new java.awt.Color(0,0,0,1));
        
        //jDateDeNaissance.setBackground(new java.awt.Color(0,0,0,1));
        
        textTéléphone__Inscription.setBackground(new java.awt.Color(0,0,0,1));
        textEmail_Inscription.setBackground(new java.awt.Color(0,0,0,1));
        textpassword_Inscription.setBackground(new java.awt.Color(0,0,0,1));        
        textpasswordRetape__Inscription.setBackground(new java.awt.Color(0,0,0,1));
        
        


          for( Component c : jDateChooser1_Inscription.getComponents()){

((JComponent)c).setBackground(new java.awt.Color(0,0,255));

}
 
    
        
                // Initialisation du Timer
        visibilityTimer = new Timer(2000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Masquer le mot de passe après la période spécifiée
                textpasswordRetape__Inscription.setEchoChar((char)8226);
                eyedisable2.setVisible(true);
                eyedisable2.setEnabled(true);
                eyeshow2.setVisible(false);
                eyeshow2.setEnabled(false);
            }
        });
        visibilityTimer.setRepeats(false); 
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        eyedisable2 = new javax.swing.JLabel();
        eyeshow2 = new javax.swing.JLabel();
        jButton1_Inscription = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textnom_Inscription = new javax.swing.JTextField();
        textpasswordRetape__Inscription = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textadresse__Inscription = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        textTéléphone__Inscription = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        textEmail_Inscription = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        textprénom_Inscription = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        textpassword_Inscription = new javax.swing.JPasswordField();
        jDateChooser1_Inscription = new com.toedter.calendar.JDateChooser();
        eyedisable1 = new javax.swing.JLabel();
        eyeshow1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngwing.com (6).png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inscription !");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 238, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(199, 226, 255));
        jLabel3.setText("Nom : ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_user_20px.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 40, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("____________________________________________________________");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 440, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(199, 226, 255));
        jLabel6.setText("Email ou login :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("___________________________________________________________");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 420, 30));

        eyedisable2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_invisible_20px.png"))); // NOI18N
        eyedisable2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eyedisable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyedisable2MouseClicked(evt);
            }
        });
        jPanel2.add(eyedisable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, 20, 30));

        eyeshow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_visible_20px.png"))); // NOI18N
        eyeshow2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eyeshow2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeshow2MouseClicked(evt);
            }
        });
        jPanel2.add(eyeshow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, 30, 30));

        jButton1_Inscription.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1_Inscription.setForeground(new java.awt.Color(25, 118, 211));
        jButton1_Inscription.setText("Soumettre");
        jButton1_Inscription.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_Inscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_InscriptionActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1_Inscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 640, 420, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Déjà inscrit(e) ? Connectez-vous !");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Retour à la page d'accueil !");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 700, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ressources de la bibliothéque.");
        jLabel11.setAlignmentX(5.0F);
        jLabel11.setAlignmentY(0.0F);
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Si vous disposez déjà d'un compte, vous pouvez vous connecter directement");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        textnom_Inscription.setFont(textnom_Inscription.getFont().deriveFont((float)16));
        textnom_Inscription.setBorder(null);
        textnom_Inscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnom_InscriptionActionPerformed(evt);
            }
        });
        jPanel2.add(textnom_Inscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 410, 30));

        textpasswordRetape__Inscription.setFont(textpasswordRetape__Inscription.getFont().deriveFont((float)16));
        textpasswordRetape__Inscription.setBorder(null);
        jPanel2.add(textpasswordRetape__Inscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 410, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Inscrivez vous afin de disposer d'un compte utilisateur et accéder aux ");
        jLabel14.setAlignmentX(5.0F);
        jLabel14.setAlignmentY(0.0F);
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("___________________________________________________________");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 420, 30));

        textadresse__Inscription.setFont(textadresse__Inscription.getFont().deriveFont((float)16));
        textadresse__Inscription.setBorder(null);
        textadresse__Inscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textadresse__InscriptionActionPerformed(evt);
            }
        });
        jPanel2.add(textadresse__Inscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 410, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(199, 226, 255));
        jLabel16.setText("Téléphone : ");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_id_card_filled_20px.png"))); // NOI18N
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 30, 40));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(199, 226, 255));
        jLabel18.setText("Prénom :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        textTéléphone__Inscription.setFont(textTéléphone__Inscription.getFont().deriveFont((float)16));
        textTéléphone__Inscription.setBorder(null);
        textTéléphone__Inscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTéléphone__InscriptionActionPerformed(evt);
            }
        });
        textTéléphone__Inscription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textTéléphone__InscriptionKeyPressed(evt);
            }
        });
        jPanel2.add(textTéléphone__Inscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 410, 30));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("____________________________________________________________");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 440, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_employee_card_filled_20px.png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 40, 40));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(199, 226, 255));
        jLabel21.setText("Adresse :");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(199, 226, 255));
        jLabel22.setText("Date de naissance :");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, 20));

        textEmail_Inscription.setFont(textEmail_Inscription.getFont().deriveFont((float)16));
        textEmail_Inscription.setBorder(null);
        jPanel2.add(textEmail_Inscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 410, 30));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("____________________________________________________________");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 440, 20));

        textprénom_Inscription.setFont(textprénom_Inscription.getFont().deriveFont((float)16));
        textprénom_Inscription.setBorder(null);
        jPanel2.add(textprénom_Inscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 410, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(199, 226, 255));
        jLabel15.setText("Saisisser à nouveau votre mot de passe :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, -1, -1));

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("___________________________________________________________");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 420, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(199, 226, 255));
        jLabel25.setText("Mot de passe :");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("___________________________________________________________");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 420, 30));

        textpassword_Inscription.setFont(textpassword_Inscription.getFont().deriveFont((float)16));
        textpassword_Inscription.setBorder(null);
        jPanel2.add(textpassword_Inscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 410, 30));

        jDateChooser1_Inscription.setBackground(new java.awt.Color(0, 0, 255));
        jDateChooser1_Inscription.setForeground(new java.awt.Color(255, 255, 255));
        jDateChooser1_Inscription.setDateFormatString("dd/MM/yyyy ");
        jDateChooser1_Inscription.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel2.add(jDateChooser1_Inscription, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 430, 40));

        eyedisable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_invisible_20px.png"))); // NOI18N
        eyedisable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eyedisable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyedisable1MouseClicked(evt);
            }
        });
        jPanel2.add(eyedisable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 20, 30));

        eyeshow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_visible_20px.png"))); // NOI18N
        eyeshow1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eyeshow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeshow1MouseClicked(evt);
            }
        });
        jPanel2.add(eyeshow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 30, 30));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_address_20px.png"))); // NOI18N
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 40, 40));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_phone_20px.png"))); // NOI18N
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 40, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("X");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eyedisable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyedisable2MouseClicked
        // TODO add your handling code here:
        textpasswordRetape__Inscription.setEchoChar((char)0);
        eyedisable2.setVisible(false);
        eyedisable2.setEnabled(false);

        eyeshow2.setVisible(true);
        eyeshow2.setEnabled(true);

        // Définir une période de visibilité de 3 secondes pour eyedisable
        visibilityTimer.setDelay(3000);
        visibilityTimer.start();

    }//GEN-LAST:event_eyedisable2MouseClicked

    private void eyeshow2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeshow2MouseClicked
        // TODO add your handling code here:
        textpasswordRetape__Inscription.setEchoChar((char)8226);
        eyedisable2.setVisible(true);
        eyedisable2.setEnabled(true);

        eyeshow2.setVisible(false);
        eyeshow2.setEnabled(false);

        // Définir une période de visibilité de 5 secondes pour eyeshow
        visibilityTimer.setDelay(5000);
        visibilityTimer.start();
    }//GEN-LAST:event_eyeshow2MouseClicked

    private void jButton1_InscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_InscriptionActionPerformed
        // TODO add your handling code here:
        
        String fname = textprénom_Inscription.getText(); // fname : first name; prénom
        String lname = textnom_Inscription.getText();    // lname : last name; nom
        String adresse = textadresse__Inscription.getText();
        
        String bdate = null ;
        //String bdate = jDateChooser1_Inscription.getDateFormatString();
        //SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
        //String bdate = dateformat.format(jDateChooser1_Inscription.getDate());
        
        String telephone = textTéléphone__Inscription.getText();
        String email = textEmail_Inscription.getText();
        
        String Mot_de_passe = String.valueOf(textpassword_Inscription.getPassword());
        String Mot_de_passe_retype = String.valueOf(textpasswordRetape__Inscription.getPassword());
        
        String Fonction_Inscription = "Utilisateur";
        
        
        if(fname.equals("")){
        
                JOptionPane.showMessageDialog(null, "Saisisser votre Prénom : !!!");
        
        }
         else if(lname.equals("")){
        
                JOptionPane.showMessageDialog(null, "Saisisser votre Nom : !!!");
        
        }
         else if(adresse.equals("")){
        
                JOptionPane.showMessageDialog(null, "Saisisser votre Adresse : !!!");
        
        }
         else if(jDateChooser1_Inscription.getDate() == null){
        
                JOptionPane.showMessageDialog(null, "Saisisser votre Date de naissance : !!!");
        
            if(jDateChooser1_Inscription.getDate() != null){
            
                    SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
                    bdate =  dateformat.format(jDateChooser1_Inscription.getDate());
         }
        }
         else if(telephone.equals("")){
        
                JOptionPane.showMessageDialog(null, "Saisisser votre Numéro de téléphone : !!!");
        
        }
         else if(telephone.length() != 9){
        
                JOptionPane.showMessageDialog(null, "Votre Numéro de téléphone doit être composé de 9 chiffres : !!!");
        
        }
        else if(email.equals("")){
        
                JOptionPane.showMessageDialog(null, "Saisisser votre adresse Email ou un pseudo");
        
        }else if(Mot_de_passe.equals("")){
            
                JOptionPane.showMessageDialog(null, "Saisisser un mot de passe");
                
        
        }else if(Mot_de_passe_retype.equals("")){
            
                JOptionPane.showMessageDialog(null, "Saisisser à nouveau le mot de passe");
                
        }
        else if(!Mot_de_passe.equals(Mot_de_passe_retype)){
            
                JOptionPane.showMessageDialog(null, "Saisisser le mot de passe encore.\nLes deux mots de passe ne correspondent pas !!! ");      
        
        }else {
        
        PreparedStatement ps;
        //Préparation de la requête sql :
        
        String query = "INSERT INTO `utilisateurs`(`Prenom`, `Nom`, `Adresse`, `Date_de_naissance`, `Telephone`, `Email_Login`, `Mot_de_Passe`, `Fonction`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        
                try {
                    ps = MyConnection.getConnection().prepareStatement(query);

                    ps.setString(1, fname);
                    ps.setString(2, lname);
                    ps.setString(3, adresse);
                    ps.setString(4, bdate);
                    ps.setString(5, telephone);
                    ps.setString(6, email);
                    ps.setString(7, Mot_de_passe);
                    ps.setString(8, Fonction_Inscription);



                    if(ps.executeUpdate() > 0){


                        // Désactivation de la page d'inscription une fois l'inscription effectué! 
                        inscription inscription = new inscription(); 
                        dispose();
                        
                        //JOptionPane.showMessageDialog(null, "Inscription effectué avec Succés !!!");
                        JOptionPane.showMessageDialog(null, "Inscription effectué avec Succés !!!\nVous Pouver vous Connecter");

                        
                        // Affichage de la page de connection une fois le clic réaliser sur le boutton se connecter ! 
                        connexion connexion = new connexion(); 
                        connexion.setVisible(true);

                    }



                } catch (SQLException ex) {
                    Logger.getLogger(inscription.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        
    }//GEN-LAST:event_jButton1_InscriptionActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        connexion connexion  = new connexion();
        connexion.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        accueil accueil  = new accueil();
        accueil.setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        //System.exit(0);        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void textadresse__InscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textadresse__InscriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textadresse__InscriptionActionPerformed

    private void textnom_InscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnom_InscriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnom_InscriptionActionPerformed

    private void textTéléphone__InscriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textTéléphone__InscriptionKeyPressed
        // TODO add your handling code here:
        // action to do when key is press
        //get jtextfield string
        String numéroTéléphone = textTéléphone__Inscription.getText();
        // get length of string
        int length = numéroTéléphone.length();
        char c = evt.getKeyChar();
        
        // check for number 0 to 9
        if (evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            // check for length not more than 9 digit
            if (length<9){
                // editable true
                textTéléphone__Inscription.setEditable(true);
            }else {
                // not editable if length more than 9 digit
                textTéléphone__Inscription.setEditable(false);
            }
        
        }else {
            // now allow keys 'back space' and 'delete' for edit
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
            
                // than allow editable
                textTéléphone__Inscription.setEditable(true);
                
            }else {
                textTéléphone__Inscription.setEditable(false);
            }
        
        }
        
    }//GEN-LAST:event_textTéléphone__InscriptionKeyPressed

    private void textTéléphone__InscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTéléphone__InscriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTéléphone__InscriptionActionPerformed

    private void eyedisable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyedisable1MouseClicked
        // TODO add your handling code here:
                textpassword_Inscription.setEchoChar((char)0);
        eyedisable1.setVisible(false);
        eyedisable1.setEnabled(false);

        eyeshow1.setVisible(true);
        eyeshow1.setEnabled(true);

        // Définir une période de visibilité de 3 secondes pour eyedisable
        visibilityTimer.setDelay(3000);
        visibilityTimer.start();
    }//GEN-LAST:event_eyedisable1MouseClicked

    private void eyeshow1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeshow1MouseClicked
        // TODO add your handling code here:
                textpassword_Inscription.setEchoChar((char)8226);
        eyedisable1.setVisible(true);
        eyedisable1.setEnabled(true);

        eyeshow1.setVisible(false);
        eyeshow1.setEnabled(false);

        // Définir une période de visibilité de 5 secondes pour eyeshow
        visibilityTimer.setDelay(5000);
        visibilityTimer.start();
    }//GEN-LAST:event_eyeshow1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inscription().setVisible(true);
            }
        });
    }

  
    private Timer visibilityTimer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eyedisable1;
    private javax.swing.JLabel eyedisable2;
    private javax.swing.JLabel eyeshow1;
    private javax.swing.JLabel eyeshow2;
    private javax.swing.JButton jButton1_Inscription;
    private com.toedter.calendar.JDateChooser jDateChooser1_Inscription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField textEmail_Inscription;
    private javax.swing.JTextField textTéléphone__Inscription;
    private javax.swing.JTextField textadresse__Inscription;
    private javax.swing.JTextField textnom_Inscription;
    private javax.swing.JPasswordField textpasswordRetape__Inscription;
    private javax.swing.JPasswordField textpassword_Inscription;
    private javax.swing.JTextField textprénom_Inscription;
    // End of variables declaration//GEN-END:variables
}
