
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class PanelAction extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelAction() {
        initComponents();
    }
    
    public void initEvent(TableActionEvent_Livres event, int row){
    Edit_GestionLivres.addActionListener(new ActionListener(){

        @Override
        public void actionPerformed(ActionEvent e) {
            event.onEdit(row);
        }
    });

    Delete_GestionLivres.addActionListener(new ActionListener(){

        @Override
        public void actionPerformed(ActionEvent e) {
            event.onDelete(row);
        }
    });

    Edit_GestionLivres.addActionListener(new ActionListener(){

        @Override
        public void actionPerformed(ActionEvent e) {
            event.onView(row);
        }
    });

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Edit_GestionLivres = new ActionButton();
        Delete_GestionLivres = new ActionButton();
        View_GestionLivres = new ActionButton();

        Edit_GestionLivres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_edit_20px.png"))); // NOI18N
        Edit_GestionLivres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_GestionLivresActionPerformed(evt);
            }
        });

        Delete_GestionLivres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_forever_20px.png"))); // NOI18N
        Delete_GestionLivres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_GestionLivresActionPerformed(evt);
            }
        });

        View_GestionLivres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_visible_20px_1.png"))); // NOI18N
        View_GestionLivres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                View_GestionLivresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Edit_GestionLivres, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(View_GestionLivres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Delete_GestionLivres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Delete_GestionLivres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(View_GestionLivres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit_GestionLivres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Edit_GestionLivresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_GestionLivresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Edit_GestionLivresActionPerformed

    private void Delete_GestionLivresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_GestionLivresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_GestionLivresActionPerformed

    private void View_GestionLivresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_View_GestionLivresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_View_GestionLivresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ActionButton Delete_GestionLivres;
    private ActionButton Edit_GestionLivres;
    private ActionButton View_GestionLivres;
    // End of variables declaration//GEN-END:variables
}
