
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Utilisateurs extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_cotisations
     */
    public Utilisateurs() {
        initComponents();
        chargerDonneesLivres();
        
        
        
        jLabel5.setLocation(0, 8000);
        
        //this.setTitle("Page connexion");
        this.setTitle("Compte Utilisateur, Page accueil : Consultation des livres de la bibliothéque ! ");
        
        
        //Etat : Activer pour l'instant
 
    // Désactiver la visibilité de la JList
    jPanelDropdownBlack.setVisible(true);
    // Désactiver la JList pour qu'elle ne soit pas cliquable
    jPanelDropdownBlack.setEnabled(true);

        
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        




        // Définition de la position du JLabel
        jPanel2Biblio.add(TableauDeBordBlanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        jPanel2Biblio.add(TableauDeBordVert, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        jPanel2Biblio.add(GestionLivresBlanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));
        jPanel2Biblio.add(GestionLivresVert, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        
        jPanel2Biblio.add(GestionEmpruntsBlanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));
        jPanel2Biblio.add(GestionEmpruntsVert, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));
        
        jPanel2Biblio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 710, -1, -1));
       
       
       

///Pour emprunter
       TableActionEvent_Utilisateurs event;
               event = new TableActionEvent_Utilisateurs(){


            @Override
            public void onSave(int row) {
                System.out.println("Delete row : " + row);
            }
        };

        jTable1_AffichLivresUtilisateurs.getColumnModel().getColumn(9).setCellRenderer(new TableCellActionRendue_Btn_Emprunt_Utilisateur());
        jTable1_AffichLivresUtilisateurs.getColumnModel().getColumn(9).setCellEditor(new TableActionsCellEditor_Btn_Emprunt_Utilisateur(event));
        
   
        
        
    }
        
private void chargerDonneesLivres() {
    PreparedStatement ps;
    ResultSet rs;
    
    String query = "SELECT * FROM livres";
    
    try {
        ps = MyConnection.getConnection().prepareStatement(query);
        rs = ps.executeQuery();
        
        DefaultTableModel model = (DefaultTableModel) jTable1_AffichLivresUtilisateurs.getModel();
        model.setRowCount(0);
        
        while (rs.next()) {
            Object[] row = {
                rs.getInt("idLivres"),
                rs.getString("Titre"),
                rs.getString("Editeur"),
                rs.getString("Auteur"),
                rs.getString("ISBN"),
                rs.getDate("Date_de_publication"),
                rs.getString("Genre"),
                rs.getInt("Exemplaires"),
                //rs.getInt("Nombre_de_pages"),
                rs.getString("Langue")
            };
            model.addRow(row);
        }

        // Fermeture des ressources
        rs.close();
        ps.close();
    } catch (SQLException ex) {
        Logger.getLogger(connexion.class.getName()).log(Level.SEVERE, null, ex);
        //System.out.println(ex.getMessage());
    }
}
    
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2Biblio = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        GestionLivresBlanc = new javax.swing.JLabel();
        GestionEmpruntsBlanc = new javax.swing.JLabel();
        TableauDeBordBlanc = new javax.swing.JLabel();
        TableauDeBordVert = new javax.swing.JLabel();
        GestionLivresVert = new javax.swing.JLabel();
        GestionEmpruntsVert = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ShowSetting = new javax.swing.JLabel();
        DisableSetting = new javax.swing.JLabel();
        jPanelDropdownBlack = new javax.swing.JPanel();
        jLabelMonCompte = new javax.swing.JLabel();
        jLabelDéconnexion = new javax.swing.JLabel();
        jLabelMonCompte1 = new javax.swing.JLabel();
        jLabelDéconnexion1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_AffichLivresUtilisateurs = new javax.swing.JTable();
        TableauDeBordBlanc2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2Biblio.setBackground(new java.awt.Color(0, 51, 255));
        jPanel2Biblio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("X");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel2Biblio.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 20, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("© ESP-DGI/ LGLSI-B");
        jLabel5.setAlignmentX(0.75F);
        jLabel5.setAlignmentY(0.75F);
        jPanel2Biblio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_user_100px.png"))); // NOI18N
        jPanel2Biblio.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 100, 90));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Utilisateur");
        jPanel2Biblio.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        GestionLivresBlanc.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        GestionLivresBlanc.setForeground(new java.awt.Color(255, 255, 255));
        GestionLivresBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_sell_35px.png"))); // NOI18N
        GestionLivresBlanc.setText("Mes emprunts");
        GestionLivresBlanc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GestionLivresBlancMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GestionLivresBlancMouseExited(evt);
            }
        });
        jPanel2Biblio.add(GestionLivresBlanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        GestionEmpruntsBlanc.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        GestionEmpruntsBlanc.setForeground(new java.awt.Color(255, 255, 255));
        GestionEmpruntsBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_coins_35px.png"))); // NOI18N
        GestionEmpruntsBlanc.setText("Mes cotisations");
        GestionEmpruntsBlanc.setAlignmentX(0.75F);
        GestionEmpruntsBlanc.setAlignmentY(0.75F);
        GestionEmpruntsBlanc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GestionEmpruntsBlancMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GestionEmpruntsBlancMouseExited(evt);
            }
        });
        jPanel2Biblio.add(GestionEmpruntsBlanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        TableauDeBordBlanc.setBackground(new java.awt.Color(255, 255, 255));
        TableauDeBordBlanc.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        TableauDeBordBlanc.setForeground(new java.awt.Color(255, 255, 255));
        TableauDeBordBlanc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_books_35px.png"))); // NOI18N
        TableauDeBordBlanc.setText("Les livres de la biblio");
        TableauDeBordBlanc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TableauDeBordBlancMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TableauDeBordBlancMouseExited(evt);
            }
        });
        jPanel2Biblio.add(TableauDeBordBlanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        TableauDeBordVert.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        TableauDeBordVert.setForeground(new java.awt.Color(0, 255, 153));
        TableauDeBordVert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_books_35px_5.png"))); // NOI18N
        TableauDeBordVert.setText("Les livres de la biblio");
        TableauDeBordVert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableauDeBordVert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TableauDeBordVertMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TableauDeBordVertMouseExited(evt);
            }
        });
        jPanel2Biblio.add(TableauDeBordVert, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        GestionLivresVert.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        GestionLivresVert.setForeground(new java.awt.Color(0, 255, 153));
        GestionLivresVert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_sell_35px_4.png"))); // NOI18N
        GestionLivresVert.setText("Mes emprunts");
        GestionLivresVert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GestionLivresVert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GestionLivresVertMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GestionLivresVertMouseExited(evt);
            }
        });
        jPanel2Biblio.add(GestionLivresVert, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        GestionEmpruntsVert.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        GestionEmpruntsVert.setForeground(new java.awt.Color(0, 255, 153));
        GestionEmpruntsVert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_coins_35px_1.png"))); // NOI18N
        GestionEmpruntsVert.setText("Mes cotisations");
        GestionEmpruntsVert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GestionEmpruntsVert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GestionEmpruntsVertMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GestionEmpruntsVertMouseExited(evt);
            }
        });
        jPanel2Biblio.add(GestionEmpruntsVert, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        ShowSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_settings_40px.png"))); // NOI18N
        ShowSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShowSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowSettingMouseClicked(evt);
            }
        });

        DisableSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_settings_40px.png"))); // NOI18N
        DisableSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DisableSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DisableSettingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowSetting)
                    .addComponent(DisableSetting))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DisableSetting)
                    .addComponent(ShowSetting))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDropdownBlack.setForeground(new java.awt.Color(255, 255, 255));
        jPanelDropdownBlack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelDropdownBlackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelDropdownBlackMouseExited(evt);
            }
        });
        jPanelDropdownBlack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMonCompte.setBackground(new java.awt.Color(255, 51, 51));
        jLabelMonCompte.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelMonCompte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_gender_neutral_user_23px.png"))); // NOI18N
        jLabelMonCompte.setText("Mon Compte");
        jLabelMonCompte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMonCompte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMonCompteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMonCompteMouseExited(evt);
            }
        });
        jPanelDropdownBlack.add(jLabelMonCompte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabelDéconnexion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelDéconnexion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_exit_23px.png"))); // NOI18N
        jLabelDéconnexion.setText("Déconnexion");
        jLabelDéconnexion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDéconnexionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelDéconnexionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelDéconnexionMouseExited(evt);
            }
        });
        jPanelDropdownBlack.add(jLabelDéconnexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabelMonCompte1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelMonCompte1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelMonCompte1.setForeground(new java.awt.Color(0, 51, 255));
        jLabelMonCompte1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_gender_neutral_user_23px_1.png"))); // NOI18N
        jLabelMonCompte1.setText("Mon Compte");
        jLabelMonCompte1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMonCompte1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMonCompte1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMonCompte1MouseExited(evt);
            }
        });
        jPanelDropdownBlack.add(jLabelMonCompte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabelDéconnexion1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelDéconnexion1.setForeground(new java.awt.Color(0, 51, 255));
        jLabelDéconnexion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_exit_23px_1.png"))); // NOI18N
        jLabelDéconnexion1.setText("Déconnexion");
        jLabelDéconnexion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelDéconnexion1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelDéconnexion1MouseExited(evt);
            }
        });
        jPanelDropdownBlack.add(jLabelDéconnexion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jTable1_AffichLivresUtilisateurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titre", "Editeur", "Auteur", "ISBN", "Date de Publication", "Genre", "Exemplaires", "Langue", "Actions"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1_AffichLivresUtilisateurs.setRowHeight(40);
        jTable1_AffichLivresUtilisateurs.setSelectionBackground(new java.awt.Color(57, 137, 121));
        jScrollPane1.setViewportView(jTable1_AffichLivresUtilisateurs);
        if (jTable1_AffichLivresUtilisateurs.getColumnModel().getColumnCount() > 0) {
            jTable1_AffichLivresUtilisateurs.getColumnModel().getColumn(0).setMinWidth(30);
            jTable1_AffichLivresUtilisateurs.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable1_AffichLivresUtilisateurs.getColumnModel().getColumn(0).setMaxWidth(35);
            jTable1_AffichLivresUtilisateurs.getColumnModel().getColumn(1).setMinWidth(185);
            jTable1_AffichLivresUtilisateurs.getColumnModel().getColumn(1).setPreferredWidth(185);
            jTable1_AffichLivresUtilisateurs.getColumnModel().getColumn(1).setMaxWidth(190);
        }

        TableauDeBordBlanc2.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        TableauDeBordBlanc2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_books_35px_6.png"))); // NOI18N
        TableauDeBordBlanc2.setText("Les livres disponible au niveau de la bibliothéque");
        TableauDeBordBlanc2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TableauDeBordBlanc2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TableauDeBordBlanc2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2Biblio, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TableauDeBordBlanc2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jPanelDropdownBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2Biblio, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelDropdownBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TableauDeBordBlanc2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(179, 179, 179))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1253, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        //System.exit(0);        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void ShowSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowSettingMouseClicked
        // TODO add your handling code here:
  
    DisableSetting.setVisible(true);
    DisableSetting.setEnabled(true);
    ShowSetting.setVisible(false);
    ShowSetting.setEnabled(false);
    
    // Désactiver la visibilité de la JList
    jPanelDropdownBlack.setVisible(true);
    // Désactiver la JList pour qu'elle ne soit pas cliquable
    jPanelDropdownBlack.setEnabled(true);

        

    }//GEN-LAST:event_ShowSettingMouseClicked

    private void DisableSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DisableSettingMouseClicked
        // TODO add your handling code here:



  
    DisableSetting.setVisible(false);
    DisableSetting.setEnabled(false);
    ShowSetting.setVisible(true);
    ShowSetting.setEnabled(true);
     


    
    // Désactiver la visibilité de la JList
    jPanelDropdownBlack.setVisible(false);
    // Désactiver la JList pour qu'elle ne soit pas cliquable
    jPanelDropdownBlack.setEnabled(false);
    }//GEN-LAST:event_DisableSettingMouseClicked

    private void jLabelMonCompteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMonCompteMouseEntered
        // TODO add your handling code here:
       // jLabelMonCompte.setBackground(Color.BLUE);
        //jLabelMonCompte.setForeground(Color.red);
        //jPanelDropdownBlack
        jLabelMonCompte.setVisible(false);
        jLabelMonCompte1.setVisible(true);
       
    }//GEN-LAST:event_jLabelMonCompteMouseEntered

    private void jLabelDéconnexionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDéconnexionMouseEntered
        // TODO add your handling code here:
        //jLabelDéconnexion.setForeground(Color.red);
        //jLabelDéconnexion.setBackground(Color.BLUE);
        jLabelDéconnexion.setVisible(false);
        jLabelDéconnexion1.setVisible(true);

       
    }//GEN-LAST:event_jLabelDéconnexionMouseEntered

    private void jLabelMonCompteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMonCompteMouseExited
        // TODO add your handling code here:
        //jLabelMonCompte.setForeground(Color.BLACK);
        jLabelMonCompte1.setVisible(false);
        jLabelMonCompte.setVisible(true);
        

    }//GEN-LAST:event_jLabelMonCompteMouseExited

    private void jLabelDéconnexionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDéconnexionMouseExited
        // TODO add your handling code here:
        //jLabelDéconnexion.setForeground(Color.BLACK);
        jLabelDéconnexion1.setVisible(false);
        jLabelDéconnexion.setVisible(true);
        
        
    }//GEN-LAST:event_jLabelDéconnexionMouseExited

    private void jPanelDropdownBlackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDropdownBlackMouseEntered
        // TODO add your handling code here:
        /*
        jPanelDropdown.setPreferredSize(new Dimension(200, 50));
        jPanelDropdown.setBackground(new Color(0, 0, 0, 0));
        */
    }//GEN-LAST:event_jPanelDropdownBlackMouseEntered

    private void jPanelDropdownBlackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDropdownBlackMouseExited
        // TODO add your handling code here:
        //102,255,51
        //jPanelDropdown.setBackground(new Color(102,255,51));
    }//GEN-LAST:event_jPanelDropdownBlackMouseExited

    private void jLabelMonCompte1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMonCompte1MouseEntered
        // TODO add your handling code here:
        jLabelMonCompte.setVisible(false);
        jLabelMonCompte1.setVisible(true);
    }//GEN-LAST:event_jLabelMonCompte1MouseEntered

    private void jLabelMonCompte1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMonCompte1MouseExited
        // TODO add your handling code here:
        jLabelMonCompte1.setVisible(false);
        jLabelMonCompte.setVisible(true);
  
    }//GEN-LAST:event_jLabelMonCompte1MouseExited

    private void jLabelDéconnexion1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDéconnexion1MouseEntered
        // TODO add your handling code here:
        jLabelDéconnexion.setVisible(false);
        jLabelDéconnexion1.setVisible(true);
        
    }//GEN-LAST:event_jLabelDéconnexion1MouseEntered

    private void jLabelDéconnexion1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDéconnexion1MouseExited
        // TODO add your handling code here:
        jLabelDéconnexion1.setVisible(false);
        jLabelDéconnexion.setVisible(true);
    }//GEN-LAST:event_jLabelDéconnexion1MouseExited

    private void TableauDeBordBlancMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableauDeBordBlancMouseEntered
        // TODO add your handling code here:
        TableauDeBordBlanc.setVisible(false);
        TableauDeBordVert.setVisible(true);
    }//GEN-LAST:event_TableauDeBordBlancMouseEntered

    private void TableauDeBordBlancMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableauDeBordBlancMouseExited
        // TODO add your handling code here:
        TableauDeBordVert.setVisible(false);
        TableauDeBordBlanc.setVisible(true);
    }//GEN-LAST:event_TableauDeBordBlancMouseExited

    private void TableauDeBordVertMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableauDeBordVertMouseEntered
        // TODO add your handling code here:
        TableauDeBordBlanc.setVisible(false);
        TableauDeBordVert.setVisible(true);
        
    }//GEN-LAST:event_TableauDeBordVertMouseEntered

    private void TableauDeBordVertMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableauDeBordVertMouseExited
        // TODO add your handling code here:
        TableauDeBordVert.setVisible(false);
        TableauDeBordBlanc.setVisible(true);
    }//GEN-LAST:event_TableauDeBordVertMouseExited

    private void GestionLivresBlancMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionLivresBlancMouseEntered
        // TODO add your handling code here:
        GestionLivresBlanc.setVisible(false);
        GestionLivresVert.setVisible(true);
    }//GEN-LAST:event_GestionLivresBlancMouseEntered

    private void GestionLivresBlancMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionLivresBlancMouseExited
        // TODO add your handling code here:
        GestionLivresVert.setVisible(false);
        GestionLivresBlanc.setVisible(true);
    }//GEN-LAST:event_GestionLivresBlancMouseExited

    private void GestionLivresVertMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionLivresVertMouseEntered
        // TODO add your handling code here:
        GestionLivresBlanc.setVisible(false);
        GestionLivresVert.setVisible(true);
        
    }//GEN-LAST:event_GestionLivresVertMouseEntered

    private void GestionLivresVertMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionLivresVertMouseExited
        // TODO add your handling code here:
        GestionLivresVert.setVisible(false);
        GestionLivresBlanc.setVisible(true);
    }//GEN-LAST:event_GestionLivresVertMouseExited

    private void GestionEmpruntsBlancMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionEmpruntsBlancMouseEntered
        // TODO add your handling code here:
        GestionEmpruntsBlanc.setVisible(false);
        GestionEmpruntsVert.setVisible(true);
    }//GEN-LAST:event_GestionEmpruntsBlancMouseEntered

    private void GestionEmpruntsBlancMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionEmpruntsBlancMouseExited
        // TODO add your handling code here:
        GestionEmpruntsVert.setVisible(false);
        GestionEmpruntsBlanc.setVisible(true);
        
    }//GEN-LAST:event_GestionEmpruntsBlancMouseExited

    private void GestionEmpruntsVertMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionEmpruntsVertMouseEntered
        // TODO add your handling code here:
        GestionEmpruntsBlanc.setVisible(false);
        GestionEmpruntsVert.setVisible(true);
    }//GEN-LAST:event_GestionEmpruntsVertMouseEntered

    private void GestionEmpruntsVertMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionEmpruntsVertMouseExited
        // TODO add your handling code here:
        GestionEmpruntsVert.setVisible(false);
        GestionEmpruntsBlanc.setVisible(true);
    }//GEN-LAST:event_GestionEmpruntsVertMouseExited

    private void TableauDeBordBlanc2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableauDeBordBlanc2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TableauDeBordBlanc2MouseEntered

    private void TableauDeBordBlanc2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableauDeBordBlanc2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_TableauDeBordBlanc2MouseExited

    private void jLabelDéconnexionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDéconnexionMouseClicked
        // TODO add your handling code here:
        dispose();
        //System.exit(0);
    }//GEN-LAST:event_jLabelDéconnexionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_cotisations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_cotisations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_cotisations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_cotisations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utilisateurs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DisableSetting;
    private javax.swing.JLabel GestionEmpruntsBlanc;
    private javax.swing.JLabel GestionEmpruntsVert;
    private javax.swing.JLabel GestionLivresBlanc;
    private javax.swing.JLabel GestionLivresVert;
    private javax.swing.JLabel ShowSetting;
    private javax.swing.JLabel TableauDeBordBlanc;
    private javax.swing.JLabel TableauDeBordBlanc2;
    private javax.swing.JLabel TableauDeBordVert;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDéconnexion;
    private javax.swing.JLabel jLabelDéconnexion1;
    private javax.swing.JLabel jLabelMonCompte;
    private javax.swing.JLabel jLabelMonCompte1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2Biblio;
    private javax.swing.JPanel jPanelDropdownBlack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_AffichLivresUtilisateurs;
    // End of variables declaration//GEN-END:variables
}
